
-- DNCC employee exit / IT takeover + accessory registry
-- Preserves existing submissions and device history. Adds new lifecycle records only.

create table if not exists public.employee_it_status (
  employee_id text primary key,
  employee_name text,
  company_email text,
  personal_email text,
  location text,
  designation text,
  status text not null default 'Active' check (status in ('Active','Exited')),
  exit_date date,
  takeover_id bigint,
  takeover_completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.employee_takeovers (
  id bigint generated by default as identity primary key,
  submission_id bigint,
  employee_id text not null,
  employee_name text,
  company_email text,
  personal_email text,
  location text,
  designation text,
  exit_date date,
  status text not null default 'Completed' check (status in ('Pending','Completed','Cancelled')),
  items_snapshot jsonb not null default '[]'::jsonb,
  notes text,
  completed_by text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.accessory_assets (
  id bigint generated by default as identity primary key,
  asset_type text not null check (asset_type in ('Charger','USB/Data Cable','SIM Card','Memory Card','Other')),
  label text,
  identifier text,
  status text not null default 'Spare' check (status in ('Assigned','Spare','With Device','Missing','Retired')),
  assigned_employee_id text,
  assigned_employee_name text,
  assigned_employee_email text,
  device_imei text,
  condition text default 'Good',
  source text,
  source_ref text unique,
  notes text,
  takeover_id bigint references public.employee_takeovers(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_employee_it_status_status on public.employee_it_status(status);
create index if not exists idx_employee_takeovers_employee on public.employee_takeovers(employee_id, completed_at desc);
create index if not exists idx_accessory_assets_status on public.accessory_assets(status);
create index if not exists idx_accessory_assets_employee on public.accessory_assets(assigned_employee_id);
create index if not exists idx_accessory_assets_device on public.accessory_assets(device_imei);
create unique index if not exists uq_accessory_sim_number
  on public.accessory_assets(identifier)
  where asset_type='SIM Card' and identifier is not null and identifier <> '' and identifier <> '0000000000';

alter table public.employee_it_status enable row level security;
alter table public.employee_takeovers enable row level security;
alter table public.accessory_assets enable row level security;

drop policy if exists "dncc_employee_it_status_all" on public.employee_it_status;
create policy "dncc_employee_it_status_all" on public.employee_it_status for all to anon, authenticated using (true) with check (true);
drop policy if exists "dncc_employee_takeovers_all" on public.employee_takeovers;
create policy "dncc_employee_takeovers_all" on public.employee_takeovers for all to anon, authenticated using (true) with check (true);
drop policy if exists "dncc_accessory_assets_all" on public.accessory_assets;
create policy "dncc_accessory_assets_all" on public.accessory_assets for all to anon, authenticated using (true) with check (true);

grant select, insert, update, delete on public.employee_it_status to anon, authenticated;
grant select, insert, update, delete on public.employee_takeovers to anon, authenticated;
grant select, insert, update, delete on public.accessory_assets to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

create or replace function public.dncc_complete_employee_takeover(
  p_submission_id bigint,
  p_employee_id text,
  p_employee_name text,
  p_company_email text,
  p_personal_email text,
  p_location text,
  p_designation text,
  p_exit_date date,
  p_items jsonb,
  p_completed_by text,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_takeover_id bigint;
  v_item jsonb;
  v_type text;
  v_identifier text;
  v_imei text;
  v_returned boolean;
  v_destination text;
  v_status text;
  v_source_ref text;
  v_keep_sims jsonb;
  v_phone jsonb;
begin
  if coalesce(trim(p_employee_id),'')='' then
    raise exception 'Employee ID is required for takeover.';
  end if;
  if coalesce(trim(p_completed_by),'')='' then
    raise exception 'IT person name is required.';
  end if;
  if p_exit_date is null then
    raise exception 'Exit date is required.';
  end if;

  insert into public.employee_takeovers(
    submission_id,employee_id,employee_name,company_email,personal_email,location,designation,
    exit_date,status,items_snapshot,notes,completed_by,completed_at
  ) values (
    p_submission_id,p_employee_id,p_employee_name,nullif(trim(p_company_email),''),nullif(trim(p_personal_email),''),
    p_location,p_designation,p_exit_date,'Completed',coalesce(p_items,'[]'::jsonb),p_notes,p_completed_by,now()
  ) returning id into v_takeover_id;

  -- Process all returned phones first.
  for v_item in select value from jsonb_array_elements(coalesce(p_items,'[]'::jsonb))
  loop
    v_type := coalesce(v_item->>'type','');
    if v_type='Mobile Phone' then
      v_imei := regexp_replace(coalesce(v_item->>'device_imei',v_item->>'identifier',''),'\D','','g');
      v_returned := coalesce((v_item->>'returned')::boolean,false);
      if not v_returned then
        raise exception 'All assigned mobile phones must be returned before takeover can be completed.';
      end if;
      if v_imei <> '' then
        select coalesce(jsonb_agg(x->>'identifier'),'[]'::jsonb) into v_keep_sims
        from jsonb_array_elements(coalesce(p_items,'[]'::jsonb)) x
        where x->>'type'='SIM Card'
          and coalesce((x->>'returned')::boolean,false)=true
          and x->>'destination'='Keep with phone'
          and regexp_replace(coalesce(x->>'device_imei',''),'\D','','g')=v_imei;

        update public.devices
        set status='Spare',
            assigned_to=null,
            assigned_employee_id=null,
            assigned_employee_email=null,
            sim_numbers=coalesce(v_keep_sims,'[]'::jsonb),
            sim_assignment_mode=case when jsonb_array_length(coalesce(v_keep_sims,'[]'::jsonb))>0 then 'SIM kept with returned phone' else 'SIM removed during employee exit takeover' end,
            condition=coalesce(nullif(v_item->>'condition',''),condition),
            last_updated=now()
        where regexp_replace(coalesce(imei1,''),'\D','','g')=v_imei;

        insert into public.device_history(imei1,action,employee_name,notes)
        values(v_imei,'Employee exit takeover',p_employee_name,'Returned to IT and moved to Spare. Takeover # '||v_takeover_id);
      end if;
    end if;
  end loop;

  -- Process accessories, SIMs and memory cards separately.
  for v_item in select value from jsonb_array_elements(coalesce(p_items,'[]'::jsonb))
  loop
    v_type := coalesce(v_item->>'type','');
    if v_type <> 'Mobile Phone' then
      v_identifier := nullif(trim(coalesce(v_item->>'identifier','')),'');
      v_imei := nullif(regexp_replace(coalesce(v_item->>'device_imei',''),'\D','','g'),'');
      v_returned := coalesce((v_item->>'returned')::boolean,false);
      v_destination := coalesce(v_item->>'destination','Spare stock');
      v_status := case
        when not v_returned then 'Missing'
        when v_destination='Keep with phone' then 'With Device'
        else 'Spare'
      end;
      v_source_ref := nullif(trim(coalesce(v_item->>'source_ref','')),'');
      if v_source_ref is null then
        v_source_ref := 'takeover:'||v_takeover_id||':'||md5(coalesce(v_type,'')||':'||coalesce(v_identifier,'')||':'||coalesce(v_imei,'')||':'||random()::text);
      end if;

      insert into public.accessory_assets(
        asset_type,label,identifier,status,assigned_employee_id,assigned_employee_name,assigned_employee_email,
        device_imei,condition,source,source_ref,notes,takeover_id,updated_at
      ) values (
        v_type,coalesce(nullif(v_item->>'label',''),v_type),v_identifier,v_status,
        null,null,null,
        case when v_status='With Device' or v_status='Missing' then v_imei else null end,
        coalesce(nullif(v_item->>'condition',''),'Good'),
        'Employee exit takeover',v_source_ref,nullif(v_item->>'notes',''),v_takeover_id,now()
      )
      on conflict(source_ref) do update set
        asset_type=excluded.asset_type,
        label=excluded.label,
        identifier=excluded.identifier,
        status=excluded.status,
        assigned_employee_id=null,
        assigned_employee_name=null,
        assigned_employee_email=null,
        device_imei=excluded.device_imei,
        condition=excluded.condition,
        source='Employee exit takeover',
        notes=excluded.notes,
        takeover_id=v_takeover_id,
        updated_at=now();
    end if;
  end loop;

  insert into public.employee_it_status(
    employee_id,employee_name,company_email,personal_email,location,designation,status,exit_date,takeover_id,takeover_completed_at,updated_at
  ) values (
    p_employee_id,p_employee_name,nullif(trim(p_company_email),''),nullif(trim(p_personal_email),''),
    p_location,p_designation,'Exited',p_exit_date,v_takeover_id,now(),now()
  )
  on conflict(employee_id) do update set
    employee_name=excluded.employee_name,
    company_email=excluded.company_email,
    personal_email=excluded.personal_email,
    location=excluded.location,
    designation=excluded.designation,
    status='Exited',
    exit_date=excluded.exit_date,
    takeover_id=v_takeover_id,
    takeover_completed_at=now(),
    updated_at=now();

  return jsonb_build_object('ok',true,'takeover_id',v_takeover_id,'completed_at',now());
end;
$$;

grant execute on function public.dncc_complete_employee_takeover(bigint,text,text,text,text,text,text,date,jsonb,text,text) to anon, authenticated;

notify pgrst, 'reload schema';
