
-- DNCC simplified lifecycle core (18-point conflict prevention)
-- Current truth:
--   phones/SIM placement -> devices
--   chargers/cables/memory/other -> accessory_assets
--   submissions -> historical evidence only
-- Employee identity: employee_id only.

create table if not exists public.dncc_employee_master (
  employee_id text primary key,
  employee_name text not null,
  company_email text,
  personal_email text,
  department text,
  location text,
  designation text,
  status text not null default 'Active' check (status in ('Active','Exited')),
  updated_at timestamptz not null default now()
);

create table if not exists public.dncc_operation_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  event_type text not null,
  employee_id text,
  old_imei text,
  new_imei text,
  details jsonb not null default '{}'::jsonb,
  changed_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.dncc_email_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  subject text,
  created_at timestamptz not null default now()
);

create index if not exists idx_dncc_operation_events_employee on public.dncc_operation_events(employee_id,created_at desc);

alter table public.dncc_employee_master enable row level security;
alter table public.dncc_operation_events enable row level security;
alter table public.dncc_email_events enable row level security;

drop policy if exists "dncc_employee_master_all" on public.dncc_employee_master;
create policy "dncc_employee_master_all" on public.dncc_employee_master for all to anon,authenticated using (true) with check (true);
drop policy if exists "dncc_operation_events_all" on public.dncc_operation_events;
create policy "dncc_operation_events_all" on public.dncc_operation_events for all to anon,authenticated using (true) with check (true);
drop policy if exists "dncc_email_events_all" on public.dncc_email_events;
create policy "dncc_email_events_all" on public.dncc_email_events for all to anon,authenticated using (true) with check (true);

grant select,insert,update on public.dncc_employee_master to anon,authenticated;
grant select,insert on public.dncc_operation_events to anon,authenticated;
grant select,insert on public.dncc_email_events to anon,authenticated;
grant usage,select on all sequences in schema public to anon,authenticated;

-- Backfill one row per Employee ID from the newest submission.
insert into public.dncc_employee_master(employee_id,employee_name,company_email,personal_email,department,location,designation,status,updated_at)
select distinct on (lower(trim(s.employee_id)))
  trim(s.employee_id),coalesce(nullif(trim(s.employee_name),''),trim(s.employee_id)),
  nullif(trim(s.company_email),''),nullif(trim(s.personal_email),''),
  nullif(trim(s.department),''),nullif(trim(s.location),''),nullif(trim(s.designation),''),
  coalesce(e.status,'Active'),now()
from public.submissions s
left join public.employee_it_status e on lower(trim(e.employee_id))=lower(trim(s.employee_id))
where coalesce(trim(s.employee_id),'')<>''
order by lower(trim(s.employee_id)),s.created_at desc
on conflict(employee_id) do update set
  employee_name=excluded.employee_name,
  company_email=excluded.company_email,
  personal_email=excluded.personal_email,
  department=excluded.department,
  location=excluded.location,
  designation=excluded.designation,
  status=excluded.status,
  updated_at=now();

create or replace function public.dncc_sync_employee_master_from_submission()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if coalesce(trim(new.employee_id),'')='' then return new; end if;
  insert into public.dncc_employee_master(employee_id,employee_name,company_email,personal_email,department,location,designation,status,updated_at)
  values(
    trim(new.employee_id),coalesce(nullif(trim(new.employee_name),''),trim(new.employee_id)),
    nullif(trim(new.company_email),''),nullif(trim(new.personal_email),''),
    nullif(trim(new.department),''),nullif(trim(new.location),''),nullif(trim(new.designation),''),
    coalesce((select status from public.employee_it_status where lower(trim(employee_id))=lower(trim(new.employee_id)) limit 1),'Active'),
    now()
  )
  on conflict(employee_id) do update set
    employee_name=excluded.employee_name,company_email=excluded.company_email,personal_email=excluded.personal_email,
    department=excluded.department,location=excluded.location,designation=excluded.designation,updated_at=now();
  return new;
end;
$$;

drop trigger if exists trg_dncc_sync_employee_master_from_submission on public.submissions;
create trigger trg_dncc_sync_employee_master_from_submission
after insert or update of employee_id,employee_name,company_email,personal_email,department,location,designation
on public.submissions
for each row execute function public.dncc_sync_employee_master_from_submission();

create or replace function public.dncc_sync_employee_master_status()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  update public.dncc_employee_master
  set status=new.status,updated_at=now()
  where lower(trim(employee_id))=lower(trim(new.employee_id));
  return new;
end;
$$;

drop trigger if exists trg_dncc_sync_employee_master_status on public.employee_it_status;
create trigger trg_dncc_sync_employee_master_status
after insert or update of status on public.employee_it_status
for each row execute function public.dncc_sync_employee_master_status();

create or replace function public.dncc_claim_email_event(p_event_key text,p_subject text default null)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare v_id bigint;
begin
  insert into public.dncc_email_events(event_key,subject)
  values(p_event_key,p_subject)
  on conflict(event_key) do nothing
  returning id into v_id;
  return v_id is not null;
end;
$$;

create or replace function public.dncc_employee_row(p_employee_id text)
returns public.dncc_employee_master
language sql
security definer
set search_path=public
as $$
  select * from public.dncc_employee_master where lower(trim(employee_id))=lower(trim(p_employee_id)) limit 1
$$;

create or replace function public.dncc_assign_device_op(
  p_imei text,p_employee_id text,p_changed_by text default 'IT Admin',p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  d public.devices%rowtype;
  e public.dncc_employee_master%rowtype;
  v_imei text:=regexp_replace(coalesce(p_imei,''),'\D','','g');
  v_event text;
begin
  select * into e from public.dncc_employee_master where lower(trim(employee_id))=lower(trim(p_employee_id)) for update;
  if not found then raise exception 'Employee ID % is not in Employee Master.',p_employee_id; end if;
  if e.status<>'Active' then raise exception 'Employee % is Exited. Reactivate before assigning a device.',p_employee_id; end if;

  select * into d from public.devices
  where regexp_replace(coalesce(imei1,''),'\D','','g')=v_imei
  limit 1 for update;
  if not found then raise exception 'Device IMEI % not found.',v_imei; end if;
  if d.status='Retired' then raise exception 'Retired device cannot be assigned.'; end if;
  if d.status='Assigned' then
    if lower(trim(coalesce(d.assigned_employee_id,'')))=lower(trim(p_employee_id)) then
      raise exception 'This device is already assigned to this employee.';
    end if;
    raise exception 'This device is already assigned to employee %. Use Replace/Return first.',coalesce(d.assigned_employee_id,d.assigned_to);
  end if;
  if d.status<>'Spare' then raise exception 'Only a Spare device can be assigned. Current status: %',d.status; end if;

  update public.devices
  set status='Assigned',assigned_to=e.employee_name,assigned_employee_id=e.employee_id,
      assigned_employee_email=coalesce(nullif(e.company_email,''),nullif(e.personal_email,'')),
      last_updated=now()
  where id=d.id;

  insert into public.device_history(imei1,action,employee_name,notes)
  values(d.imei1,'Assigned via Daily Operations',e.employee_name,concat_ws(' · ',nullif(p_note,''),'Employee ID '||e.employee_id));

  v_event:='assign:'||v_imei||':'||lower(trim(e.employee_id))||':'||extract(epoch from now())::bigint;
  insert into public.dncc_operation_events(event_key,event_type,employee_id,new_imei,details,changed_by)
  values(v_event,'Assign Device',e.employee_id,d.imei1,jsonb_build_object('note',p_note),p_changed_by);

  return jsonb_build_object('ok',true,'event_key',v_event,'employee_id',e.employee_id,'imei',d.imei1);
end;
$$;

create or replace function public.dncc_return_device_op(
  p_imei text,p_keep_sims boolean default true,p_changed_by text default 'IT Admin',p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  d public.devices%rowtype;
  v_imei text:=regexp_replace(coalesce(p_imei,''),'\D','','g');
  v_emp text;
  v_name text;
  v_event text;
begin
  select * into d from public.devices
  where regexp_replace(coalesce(imei1,''),'\D','','g')=v_imei
  limit 1 for update;
  if not found then raise exception 'Device not found.'; end if;
  if d.status<>'Assigned' then raise exception 'Only an Assigned device can be returned. Current status: %',d.status; end if;
  if coalesce(trim(d.assigned_employee_id),'')='' then raise exception 'Assigned device has no Employee ID. Review consistency before return.'; end if;

  v_emp:=d.assigned_employee_id; v_name:=d.assigned_to;
  update public.devices
  set status='Spare',assigned_to=null,assigned_employee_id=null,assigned_employee_email=null,
      sim_numbers=case when p_keep_sims then sim_numbers else '[]'::jsonb end,
      sim_assignment_mode=case when p_keep_sims then 'SIM kept with returned phone' else 'SIM removed during return' end,
      last_updated=now()
  where id=d.id;

  insert into public.device_history(imei1,action,employee_name,notes)
  values(d.imei1,'Returned to IT via Daily Operations',v_name,concat_ws(' · ',nullif(p_note,''),case when p_keep_sims then 'SIM kept with phone' else 'SIM removed to stock' end));

  v_event:='return:'||v_imei||':'||lower(trim(v_emp))||':'||extract(epoch from now())::bigint;
  insert into public.dncc_operation_events(event_key,event_type,employee_id,old_imei,details,changed_by)
  values(v_event,'Return Device',v_emp,d.imei1,jsonb_build_object('keep_sims',p_keep_sims,'note',p_note),p_changed_by);

  return jsonb_build_object('ok',true,'event_key',v_event,'employee_id',v_emp,'imei',d.imei1);
end;
$$;

create or replace function public.dncc_replace_device_op(
  p_employee_id text,p_old_imei text,p_new_imei text,p_transfer_sims boolean default true,
  p_changed_by text default 'IT Admin',p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  oldd public.devices%rowtype;
  newd public.devices%rowtype;
  e public.dncc_employee_master%rowtype;
  oldn text:=regexp_replace(coalesce(p_old_imei,''),'\D','','g');
  newn text:=regexp_replace(coalesce(p_new_imei,''),'\D','','g');
  v_event text;
begin
  if oldn=newn then raise exception 'Old and replacement phone cannot be the same.'; end if;
  select * into e from public.dncc_employee_master where lower(trim(employee_id))=lower(trim(p_employee_id)) for update;
  if not found or e.status<>'Active' then raise exception 'Employee is not Active in Employee Master.'; end if;

  select * into oldd from public.devices where regexp_replace(coalesce(imei1,''),'\D','','g')=oldn limit 1 for update;
  if not found then raise exception 'Old device not found.'; end if;
  if oldd.status<>'Assigned' or lower(trim(coalesce(oldd.assigned_employee_id,'')))<>lower(trim(e.employee_id)) then
    raise exception 'Old phone is not currently assigned to employee %.',e.employee_id;
  end if;

  select * into newd from public.devices where regexp_replace(coalesce(imei1,''),'\D','','g')=newn limit 1 for update;
  if not found then raise exception 'Replacement device not found.'; end if;
  if newd.status<>'Spare' or coalesce(trim(newd.assigned_employee_id),'')<>'' or coalesce(trim(newd.assigned_to),'')<>'' then
    raise exception 'Replacement phone must be Spare and unassigned.';
  end if;

  update public.devices
  set status='Spare',assigned_to=null,assigned_employee_id=null,assigned_employee_email=null,
      sim_numbers=case when p_transfer_sims then '[]'::jsonb else sim_numbers end,
      sim_assignment_mode=case when p_transfer_sims then 'SIM transferred during replacement' else sim_assignment_mode end,
      last_updated=now()
  where id=oldd.id;

  update public.devices
  set status='Assigned',assigned_to=e.employee_name,assigned_employee_id=e.employee_id,
      assigned_employee_email=coalesce(nullif(e.company_email,''),nullif(e.personal_email,'')),
      sim_numbers=case when p_transfer_sims then oldd.sim_numbers else sim_numbers end,
      sim_assignment_mode=case when p_transfer_sims then 'SIM transferred from IMEI '||oldd.imei1 else sim_assignment_mode end,
      last_updated=now()
  where id=newd.id;

  insert into public.device_history(imei1,action,employee_name,notes)
  values(oldd.imei1,'Replaced / returned via Daily Operations',e.employee_name,concat_ws(' · ',nullif(p_note,''),'Replaced by IMEI '||newd.imei1));
  insert into public.device_history(imei1,action,employee_name,notes)
  values(newd.imei1,'Replacement assigned via Daily Operations',e.employee_name,concat_ws(' · ',nullif(p_note,''),'Replaced IMEI '||oldd.imei1));

  v_event:='replace:'||oldn||':'||newn||':'||lower(trim(e.employee_id))||':'||extract(epoch from now())::bigint;
  insert into public.dncc_operation_events(event_key,event_type,employee_id,old_imei,new_imei,details,changed_by)
  values(v_event,'Replace Device',e.employee_id,oldd.imei1,newd.imei1,jsonb_build_object('transfer_sims',p_transfer_sims,'note',p_note),p_changed_by);

  return jsonb_build_object('ok',true,'event_key',v_event,'employee_id',e.employee_id,'old_imei',oldd.imei1,'new_imei',newd.imei1);
end;
$$;

create or replace function public.dncc_retire_device_op(
  p_imei text,p_changed_by text default 'IT Admin',p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  d public.devices%rowtype;
  v_imei text:=regexp_replace(coalesce(p_imei,''),'\D','','g');
  v_event text;
begin
  select * into d from public.devices
  where regexp_replace(coalesce(imei1,''),'\D','','g')=v_imei
  limit 1 for update;
  if not found then raise exception 'Device not found.'; end if;
  if d.status='Assigned' then raise exception 'Assigned device cannot be retired. Return it first.'; end if;
  if d.status='Retired' then raise exception 'Device is already Retired.'; end if;
  if coalesce(trim(p_note),'')='' then raise exception 'Retirement reason is required.'; end if;

  update public.devices
  set status='Retired',assigned_to=null,assigned_employee_id=null,assigned_employee_email=null,last_updated=now()
  where id=d.id;

  insert into public.device_history(imei1,action,employee_name,notes)
  values(d.imei1,'Retired via Daily Operations','',p_note);

  v_event:='retire:'||v_imei||':'||extract(epoch from now())::bigint;
  insert into public.dncc_operation_events(event_key,event_type,old_imei,details,changed_by)
  values(v_event,'Retire Device',d.imei1,jsonb_build_object('reason',p_note),p_changed_by);

  return jsonb_build_object('ok',true,'event_key',v_event,'imei',d.imei1);
end;
$$;

create or replace function public.dncc_current_asset_state(p_employee_id text)
returns jsonb
language sql
security definer
set search_path=public
as $$
  select jsonb_build_object(
    'employee',(select to_jsonb(e) from public.dncc_employee_master e where lower(trim(e.employee_id))=lower(trim(p_employee_id)) limit 1),
    'devices',coalesce((select jsonb_agg(to_jsonb(d) order by d.last_updated desc) from public.devices d where d.status='Assigned' and lower(trim(coalesce(d.assigned_employee_id,'')))=lower(trim(p_employee_id))),'[]'::jsonb),
    'accessories',coalesce((select jsonb_agg(to_jsonb(a) order by a.updated_at desc) from public.accessory_assets a where a.status in ('Assigned','With Device') and lower(trim(coalesce(a.assigned_employee_id,'')))=lower(trim(p_employee_id))),'[]'::jsonb)
  )
$$;

create or replace function public.dncc_system_consistency_health()
returns table(severity text,issue_type text,entity_key text,message text)
language sql
security definer
set search_path=public
as $$
  select 'High','AssignedDeviceMissingEmployee','IMEI:'||coalesce(d.imei1,''),
         'Assigned device '||coalesce(d.imei1,'')||' has no Employee ID.'
  from public.devices d
  where d.status='Assigned' and coalesce(trim(d.assigned_employee_id),'')=''

  union all
  select 'High','AssignedDeviceUnknownEmployee','IMEI:'||coalesce(d.imei1,''),
         'Assigned device '||coalesce(d.imei1,'')||' references Employee ID '||coalesce(d.assigned_employee_id,'')||' which is not in Employee Master.'
  from public.devices d
  where d.status='Assigned' and coalesce(trim(d.assigned_employee_id),'')<>''
    and not exists(select 1 from public.dncc_employee_master e where lower(trim(e.employee_id))=lower(trim(d.assigned_employee_id)))

  union all
  select 'High','ExitedEmployeeOwnsDevice','EMP:'||e.employee_id,
         'Exited employee '||e.employee_id||' still has assigned phone IMEI '||coalesce(d.imei1,'')||'.'
  from public.dncc_employee_master e
  join public.devices d on lower(trim(coalesce(d.assigned_employee_id,'')))=lower(trim(e.employee_id)) and d.status='Assigned'
  where e.status='Exited'

  union all
  select 'High','ExitedEmployeeOwnsAccessory','EMP:'||e.employee_id,
         'Exited employee '||e.employee_id||' still has accessory ACC-'||lpad(a.id::text,6,'0')||'.'
  from public.dncc_employee_master e
  join public.accessory_assets a on lower(trim(coalesce(a.assigned_employee_id,'')))=lower(trim(e.employee_id)) and a.status in ('Assigned','With Device')
  where e.status='Exited'

  union all
  select 'High','DuplicateSIMAcrossDevices','SIM:'||x.sim_no,
         'SIM '||x.sim_no||' appears on more than one device.'
  from (
    select regexp_replace(s.value,'\D','','g') sim_no,count(distinct d.id) n
    from public.devices d
    cross join lateral jsonb_array_elements_text(coalesce(d.sim_numbers,'[]'::jsonb)) s(value)
    where regexp_replace(s.value,'\D','','g') ~ '^\d{10}$'
      and regexp_replace(s.value,'\D','','g')<>'0000000000'
    group by regexp_replace(s.value,'\D','','g')
    having count(distinct d.id)>1
  ) x

  union all
  select 'Medium','AccessoryMissingEmployee','ACC:'||a.id,
         'Accessory ACC-'||lpad(a.id::text,6,'0')||' is Assigned but has no Employee ID.'
  from public.accessory_assets a
  where a.status='Assigned' and coalesce(trim(a.assigned_employee_id),'')=''

  union all
  select 'Medium','DeviceLinkedAccessoryMissingPhone','ACC:'||a.id,
         'Accessory ACC-'||lpad(a.id::text,6,'0')||' is With Device but linked phone is missing.'
  from public.accessory_assets a
  where a.status='With Device'
    and coalesce(trim(a.device_imei),'')<>''
    and not exists(
      select 1 from public.devices d
      where regexp_replace(coalesce(d.imei1,''),'\D','','g')=regexp_replace(coalesce(a.device_imei,''),'\D','','g')
    );
$$;

grant execute on function public.dncc_claim_email_event(text,text) to anon,authenticated;
grant execute on function public.dncc_assign_device_op(text,text,text,text) to anon,authenticated;
grant execute on function public.dncc_return_device_op(text,boolean,text,text) to anon,authenticated;
grant execute on function public.dncc_replace_device_op(text,text,text,boolean,text,text) to anon,authenticated;
grant execute on function public.dncc_retire_device_op(text,text,text) to anon,authenticated;
grant execute on function public.dncc_current_asset_state(text) to anon,authenticated;
grant execute on function public.dncc_system_consistency_health() to anon,authenticated;

notify pgrst,'reload schema';
