
-- DNCC Accessory Lifecycle Consistency v2
-- Purpose:
-- 1) Assignment changes only through controlled RPCs.
-- 2) SIM/device linkage stays synchronized with devices.sim_numbers.
-- 3) Every accessory change is auditable.
-- 4) Historical handover forms seed missing rows only; they are not current truth.

alter table if exists public.accessory_assets
  add column if not exists assignment_mode text,
  add column if not exists assigned_at timestamptz,
  add column if not exists returned_at timestamptz,
  add column if not exists updated_by text,
  add column if not exists manual_override boolean not null default false;

create index if not exists idx_accessory_assets_employee_status
  on public.accessory_assets(assigned_employee_id,status);
create index if not exists idx_accessory_assets_device_status
  on public.accessory_assets(device_imei,status);
create index if not exists idx_accessory_assets_identifier_type
  on public.accessory_assets(asset_type,identifier);

create table if not exists public.accessory_asset_history (
  id bigint generated by default as identity primary key,
  asset_id bigint not null,
  action text not null,
  from_status text,
  to_status text,
  employee_id text,
  employee_name text,
  device_imei text,
  details jsonb not null default '{}'::jsonb,
  changed_by text,
  created_at timestamptz not null default now()
);

create index if not exists idx_accessory_history_asset_created
  on public.accessory_asset_history(asset_id,created_at desc);

alter table public.accessory_asset_history enable row level security;
drop policy if exists "dncc_accessory_history_all" on public.accessory_asset_history;
create policy "dncc_accessory_history_all"
  on public.accessory_asset_history for all to anon,authenticated
  using (true) with check (true);
grant select,insert on public.accessory_asset_history to anon,authenticated;
grant usage,select on all sequences in schema public to anon,authenticated;

-- Preserve but retire legacy duplicate SIM rows before future validation is enabled.
with ranked_sim as (
  select id,
         row_number() over(
           partition by regexp_replace(coalesce(identifier,''),'\D','','g')
           order by
             case status when 'With Device' then 1 when 'Assigned' then 2 when 'Spare' then 3 else 4 end,
             coalesce(updated_at,created_at) desc,
             id desc
         ) rn
  from public.accessory_assets
  where asset_type='SIM Card'
    and regexp_replace(coalesce(identifier,''),'\D','','g') ~ '^\d{10}$'
    and regexp_replace(coalesce(identifier,''),'\D','','g') <> '0000000000'
)
update public.accessory_assets a
set asset_type='Other',
    label=concat('Legacy duplicate SIM record ',coalesce(a.identifier,'')),
    identifier=null,
    status='Retired',
    assigned_employee_id=null,
    assigned_employee_name=null,
    assigned_employee_email=null,
    device_imei=null,
    assignment_mode=null,
    returned_at=now(),
    updated_by='Legacy SIM duplicate cleanup',
    notes=concat_ws(' · ',nullif(a.notes,''),'Duplicate SIM row retired during lifecycle migration'),
    updated_at=now()
where a.id in (select id from ranked_sim where rn>1);

-- Normalize SIM numbers and block future duplicate/invalid SIM rows.
create or replace function public.dncc_accessory_validate()
returns trigger
language plpgsql
set search_path=public
as $$
declare
  v_sim text;
begin
  if new.asset_type='SIM Card' then
    v_sim:=regexp_replace(coalesce(new.identifier,''),'\D','','g');
    if v_sim !~ '^\d{10}$' or v_sim='0000000000' then
      raise exception 'SIM number must be a real 10-digit number.';
    end if;
    new.identifier:=v_sim;
    new.label:=coalesce(nullif(trim(new.label),''),'SIM '||v_sim);
    if exists(
      select 1 from public.accessory_assets a
      where a.asset_type='SIM Card'
        and regexp_replace(coalesce(a.identifier,''),'\D','','g')=v_sim
        and a.id is distinct from new.id
    ) then
      raise exception 'SIM % already exists in the accessory register.',v_sim;
    end if;
  end if;
  new.updated_at:=now();
  return new;
end;
$$;

drop trigger if exists trg_dncc_accessory_validate on public.accessory_assets;
create trigger trg_dncc_accessory_validate
before insert or update on public.accessory_assets
for each row execute function public.dncc_accessory_validate();

create or replace function public.dncc_accessory_audit()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_action text;
begin
  if tg_op='INSERT' then
    v_action:='Created';
    insert into public.accessory_asset_history(
      asset_id,action,from_status,to_status,employee_id,employee_name,device_imei,details,changed_by
    ) values (
      new.id,v_action,null,new.status,new.assigned_employee_id,new.assigned_employee_name,new.device_imei,
      jsonb_build_object('asset_type',new.asset_type,'label',new.label,'identifier',new.identifier,'source',new.source),
      coalesce(new.updated_by,'System')
    );
    return new;
  end if;

  if old.status is distinct from new.status
     or old.assigned_employee_id is distinct from new.assigned_employee_id
     or old.device_imei is distinct from new.device_imei
     or old.identifier is distinct from new.identifier
     or old.condition is distinct from new.condition
     or old.notes is distinct from new.notes then
    v_action:=case
      when old.status is distinct from new.status or old.assigned_employee_id is distinct from new.assigned_employee_id or old.device_imei is distinct from new.device_imei then 'Lifecycle update'
      else 'Metadata update'
    end;
    insert into public.accessory_asset_history(
      asset_id,action,from_status,to_status,employee_id,employee_name,device_imei,details,changed_by
    ) values (
      new.id,v_action,old.status,new.status,new.assigned_employee_id,new.assigned_employee_name,new.device_imei,
      jsonb_build_object(
        'old_employee_id',old.assigned_employee_id,'new_employee_id',new.assigned_employee_id,
        'old_device_imei',old.device_imei,'new_device_imei',new.device_imei,
        'old_identifier',old.identifier,'new_identifier',new.identifier
      ),
      coalesce(new.updated_by,'System')
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_dncc_accessory_audit on public.accessory_assets;
create trigger trg_dncc_accessory_audit
after insert or update on public.accessory_assets
for each row execute function public.dncc_accessory_audit();

-- Helper: sync a device's current SIM list and any device-linked memory/SIM asset owner.
create or replace function public.dncc_sync_accessories_from_device()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_sim text;
  v_old_sim text;
  v_existing_id bigint;
  v_emp_id text;
  v_emp_name text;
  v_emp_email text;
begin
  if new.status='Assigned' then
    v_emp_id:=nullif(trim(coalesce(new.assigned_employee_id,'')),'');
    v_emp_name:=nullif(trim(coalesce(new.assigned_to,'')),'');
    v_emp_email:=nullif(trim(coalesce(new.assigned_employee_email,'')),'');
  else
    v_emp_id:=null; v_emp_name:=null; v_emp_email:=null;
  end if;

  -- Existing SIM/memory rows physically linked to this phone follow the phone owner.
  update public.accessory_assets
  set status='With Device',
      assigned_employee_id=v_emp_id,
      assigned_employee_name=v_emp_name,
      assigned_employee_email=v_emp_email,
      assignment_mode='Device',
      updated_by='Device inventory sync',
      updated_at=now()
  where regexp_replace(coalesce(device_imei,''),'\D','','g')=regexp_replace(coalesce(new.imei1,''),'\D','','g')
    and asset_type in ('SIM Card','Memory Card')
    and status<>'Retired';

  -- Upsert every valid SIM currently recorded on the device.
  for v_sim in
    select regexp_replace(value,'\D','','g')
    from jsonb_array_elements_text(coalesce(new.sim_numbers,'[]'::jsonb))
  loop
    if v_sim ~ '^\d{10}$' and v_sim<>'0000000000' then
      select id into v_existing_id
      from public.accessory_assets
      where asset_type='SIM Card'
        and regexp_replace(coalesce(identifier,''),'\D','','g')=v_sim
      order by id
      limit 1;

      if v_existing_id is null then
        insert into public.accessory_assets(
          asset_type,label,identifier,status,assigned_employee_id,assigned_employee_name,assigned_employee_email,
          device_imei,condition,source,source_ref,assignment_mode,assigned_at,updated_by
        ) values (
          'SIM Card','SIM '||v_sim,v_sim,'With Device',v_emp_id,v_emp_name,v_emp_email,
          new.imei1,'Good','Device inventory','sim:'||v_sim,'Device',
          case when new.status='Assigned' then now() else null end,'Device inventory sync'
        );
      else
        update public.accessory_assets
        set status='With Device',
            assigned_employee_id=v_emp_id,
            assigned_employee_name=v_emp_name,
            assigned_employee_email=v_emp_email,
            device_imei=new.imei1,
            assignment_mode='Device',
            assigned_at=case when new.status='Assigned' then coalesce(assigned_at,now()) else assigned_at end,
            updated_by='Device inventory sync',
            updated_at=now()
        where id=v_existing_id;
      end if;
    end if;
  end loop;

  -- SIMs removed from this phone become Spare only if they are not present in another device.
  if tg_op='UPDATE' then
    for v_old_sim in
      select regexp_replace(value,'\D','','g')
      from jsonb_array_elements_text(coalesce(old.sim_numbers,'[]'::jsonb))
      except
      select regexp_replace(value,'\D','','g')
      from jsonb_array_elements_text(coalesce(new.sim_numbers,'[]'::jsonb))
    loop
      if v_old_sim ~ '^\d{10}$' and not exists(
        select 1
        from public.devices d
        cross join lateral jsonb_array_elements_text(coalesce(d.sim_numbers,'[]'::jsonb)) s(value)
        where d.id is distinct from new.id
          and regexp_replace(s.value,'\D','','g')=v_old_sim
      ) then
        update public.accessory_assets
        set status='Spare',assigned_employee_id=null,assigned_employee_name=null,assigned_employee_email=null,
            device_imei=null,assignment_mode=null,returned_at=now(),updated_by='Device inventory sync',updated_at=now()
        where asset_type='SIM Card'
          and regexp_replace(coalesce(identifier,''),'\D','','g')=v_old_sim
          and status<>'Retired';
      end if;
    end loop;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_dncc_sync_accessories_from_device on public.devices;
create trigger trg_dncc_sync_accessories_from_device
after insert or update of status,assigned_to,assigned_employee_id,assigned_employee_email,sim_numbers,imei1
on public.devices
for each row execute function public.dncc_sync_accessories_from_device();

create or replace function public.dncc_assign_accessory(
  p_asset_id bigint,
  p_employee_id text,
  p_employee_name text,
  p_employee_email text,
  p_assignment_mode text,
  p_device_imei text default null,
  p_changed_by text default 'IT Admin',
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  a public.accessory_assets%rowtype;
  d public.devices%rowtype;
  v_mode text:=coalesce(nullif(trim(p_assignment_mode),''),'Employee');
  v_imei text:=regexp_replace(coalesce(p_device_imei,''),'\D','','g');
  v_sim text;
  v_sims jsonb;
begin
  select * into a from public.accessory_assets where id=p_asset_id for update;
  if not found then raise exception 'Accessory not found.'; end if;
  if a.status='Retired' then raise exception 'Retired accessory cannot be assigned.'; end if;

  if exists(
    select 1 from public.employee_it_status e
    where lower(trim(e.employee_id))=lower(trim(p_employee_id))
      and e.status='Exited'
  ) then raise exception 'This employee is marked Exited. Reactivate the employee before assignment.'; end if;

  if a.asset_type in ('SIM Card','Memory Card') then v_mode:='Device'; end if;

  if v_mode='Device' then
    if a.asset_type not in ('SIM Card','Memory Card') then
      raise exception 'Only SIM Card and Memory Card can be attached to a phone. Assign this asset directly to the employee.';
    end if;
    if v_imei='' then raise exception 'Select an employee phone for this asset.'; end if;
    select * into d from public.devices
      where regexp_replace(coalesce(imei1,''),'\D','','g')=v_imei
      limit 1 for update;
    if not found then raise exception 'Selected phone was not found in inventory.'; end if;
    if d.status<>'Assigned' then raise exception 'Selected phone is not currently Assigned.'; end if;
    if coalesce(trim(d.assigned_employee_id),'')<>coalesce(trim(p_employee_id),'') then
      raise exception 'Selected phone belongs to a different employee.';
    end if;

    if a.asset_type='SIM Card' then
      v_sim:=regexp_replace(coalesce(a.identifier,''),'\D','','g');
      if v_sim !~ '^\d{10}$' then raise exception 'SIM number is invalid.'; end if;

      -- A SIM can be present on only one phone. Remove it from every other device first.
      update public.devices od
      set sim_numbers=coalesce((
            select jsonb_agg(value)
            from jsonb_array_elements_text(coalesce(od.sim_numbers,'[]'::jsonb))
            where regexp_replace(value,'\D','','g')<>v_sim
          ),'[]'::jsonb),
          sim_assignment_mode='SIM moved through Accessory Register',
          last_updated=now()
      where od.id<>d.id
        and exists(
          select 1 from jsonb_array_elements_text(coalesce(od.sim_numbers,'[]'::jsonb)) z(value)
          where regexp_replace(z.value,'\D','','g')=v_sim
        );

      select coalesce(jsonb_agg(x),'[]'::jsonb) into v_sims
      from (
        select distinct value as x
        from jsonb_array_elements_text(coalesce(d.sim_numbers,'[]'::jsonb))
        union
        select v_sim
      ) q;
      update public.devices
      set sim_numbers=v_sims,sim_assignment_mode='Accessory register assignment',last_updated=now()
      where id=d.id;
      -- Device trigger finishes owner/device synchronization. Stamp the explicit IT action.
      update public.accessory_assets
      set manual_override=true,updated_by=p_changed_by,assigned_at=now(),returned_at=null,
          notes=case when p_note is null or trim(p_note)='' then notes else trim(p_note) end,updated_at=now()
      where id=p_asset_id;
    else
      update public.accessory_assets
      set status='With Device',assigned_employee_id=p_employee_id,assigned_employee_name=p_employee_name,
          assigned_employee_email=nullif(trim(p_employee_email),''),device_imei=d.imei1,assignment_mode='Device',
          assigned_at=now(),returned_at=null,manual_override=true,updated_by=p_changed_by,
          notes=case when p_note is null or trim(p_note)='' then notes else trim(p_note) end,updated_at=now()
      where id=p_asset_id;
    end if;
  else
    if a.asset_type in ('SIM Card','Memory Card') then
      raise exception 'SIM and Memory Card must be attached to an Assigned employee phone.';
    end if;
    update public.accessory_assets
    set status='Assigned',assigned_employee_id=p_employee_id,assigned_employee_name=p_employee_name,
        assigned_employee_email=nullif(trim(p_employee_email),''),device_imei=null,assignment_mode='Employee',
        assigned_at=now(),returned_at=null,manual_override=true,updated_by=p_changed_by,
        notes=case when p_note is null or trim(p_note)='' then notes else trim(p_note) end,updated_at=now()
    where id=p_asset_id;
  end if;

  return jsonb_build_object('ok',true,'asset_id',p_asset_id,'mode',v_mode);
end;
$$;

create or replace function public.dncc_return_accessory(
  p_asset_id bigint,
  p_destination text,
  p_changed_by text default 'IT Admin',
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  a public.accessory_assets%rowtype;
  d public.devices%rowtype;
  v_dest text:=initcap(lower(trim(coalesce(p_destination,'Spare'))));
  v_sim text;
  v_sims jsonb;
begin
  if v_dest not in ('Spare','Missing','Retired') then
    raise exception 'Return destination must be Spare, Missing or Retired.';
  end if;

  select * into a from public.accessory_assets where id=p_asset_id for update;
  if not found then raise exception 'Accessory not found.'; end if;

  -- If a SIM is inside a device, remove it from device.sim_numbers first.
  if a.asset_type='SIM Card' and coalesce(trim(a.device_imei),'')<>'' then
    v_sim:=regexp_replace(coalesce(a.identifier,''),'\D','','g');
    select * into d from public.devices
      where regexp_replace(coalesce(imei1,''),'\D','','g')=regexp_replace(coalesce(a.device_imei,''),'\D','','g')
      limit 1 for update;
    if found then
      select coalesce(jsonb_agg(value),'[]'::jsonb) into v_sims
      from jsonb_array_elements_text(coalesce(d.sim_numbers,'[]'::jsonb))
      where regexp_replace(value,'\D','','g')<>v_sim;
      update public.devices
      set sim_numbers=v_sims,
          sim_assignment_mode=case when jsonb_array_length(v_sims)=0 then 'No SIM assigned' else sim_assignment_mode end,
          last_updated=now()
      where id=d.id;
    end if;
  end if;

  update public.accessory_assets
  set status=v_dest,assigned_employee_id=null,assigned_employee_name=null,assigned_employee_email=null,
      device_imei=null,assignment_mode=null,returned_at=now(),manual_override=true,updated_by=p_changed_by,
      notes=case when p_note is null or trim(p_note)='' then notes else trim(p_note) end,updated_at=now()
  where id=p_asset_id;

  return jsonb_build_object('ok',true,'asset_id',p_asset_id,'status',v_dest);
end;
$$;

-- Safe deterministic reconciliation only. It never guesses physical possession of charger/cable.
create or replace function public.dncc_reconcile_accessory_registry()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  d public.devices%rowtype;
  v_sim text;
  v_id bigint;
  v_count int:=0;
begin
  -- Sync device-linked rows from every inventory device.
  for d in select * from public.devices loop
    update public.accessory_assets
    set status='With Device',
        assigned_employee_id=case when d.status='Assigned' then d.assigned_employee_id else null end,
        assigned_employee_name=case when d.status='Assigned' then d.assigned_to else null end,
        assigned_employee_email=case when d.status='Assigned' then d.assigned_employee_email else null end,
        assignment_mode='Device',updated_by='Consistency sync',updated_at=now()
    where regexp_replace(coalesce(device_imei,''),'\D','','g')=regexp_replace(coalesce(d.imei1,''),'\D','','g')
      and asset_type in ('SIM Card','Memory Card')
      and status<>'Retired';
    get diagnostics v_count=row_count;

    for v_sim in
      select regexp_replace(value,'\D','','g')
      from jsonb_array_elements_text(coalesce(d.sim_numbers,'[]'::jsonb))
    loop
      if v_sim ~ '^\d{10}$' and v_sim<>'0000000000' then
        select id into v_id from public.accessory_assets
        where asset_type='SIM Card' and regexp_replace(coalesce(identifier,''),'\D','','g')=v_sim
        order by id limit 1;
        if v_id is null then
          insert into public.accessory_assets(
            asset_type,label,identifier,status,assigned_employee_id,assigned_employee_name,assigned_employee_email,
            device_imei,condition,source,source_ref,assignment_mode,updated_by
          ) values (
            'SIM Card','SIM '||v_sim,v_sim,'With Device',
            case when d.status='Assigned' then d.assigned_employee_id else null end,
            case when d.status='Assigned' then d.assigned_to else null end,
            case when d.status='Assigned' then d.assigned_employee_email else null end,
            d.imei1,'Good','Device inventory','sim:'||v_sim,'Device','Consistency sync'
          );
        else
          update public.accessory_assets
          set status='With Device',
              assigned_employee_id=case when d.status='Assigned' then d.assigned_employee_id else null end,
              assigned_employee_name=case when d.status='Assigned' then d.assigned_to else null end,
              assigned_employee_email=case when d.status='Assigned' then d.assigned_employee_email else null end,
              device_imei=d.imei1,assignment_mode='Device',updated_by='Consistency sync',updated_at=now()
          where id=v_id and status<>'Retired';
        end if;
      end if;
    end loop;
  end loop;

  -- Legacy auto-generated duplicate charger/cable rows for the SAME exact employee ID
  -- are demoted to Spare. Manual/takeover rows are never guessed or deleted.
  with ranked as (
    select id,row_number() over(
      partition by lower(trim(assigned_employee_id)),asset_type
      order by coalesce(updated_at,created_at) desc,id desc
    ) rn
    from public.accessory_assets
    where source='Handover form'
      and asset_type in ('Charger','USB/Data Cable')
      and status='Assigned'
      and coalesce(trim(assigned_employee_id),'')<>''
      and manual_override=false
  )
  update public.accessory_assets a
  set status='Spare',assigned_employee_id=null,assigned_employee_name=null,assigned_employee_email=null,
      assignment_mode=null,returned_at=now(),updated_by='Legacy duplicate cleanup',
      notes=concat_ws(' · ',nullif(a.notes,''),'Legacy duplicate auto-row moved to Spare'),updated_at=now()
  where a.id in (select id from ranked where rn>1);

  return jsonb_build_object('ok',true,'synced_at',now());
end;
$$;

create or replace function public.dncc_accessory_health()
returns table(severity text,issue_type text,asset_id bigint,message text)
language sql
security definer
set search_path=public
as $$
  select 'High','AssignedWithoutEmployee',a.id,
         'ACC-'||lpad(a.id::text,6,'0')||' is Assigned but has no Employee ID.'
  from public.accessory_assets a
  where a.status='Assigned' and coalesce(trim(a.assigned_employee_id),'')=''

  union all
  select 'High','WithDeviceWithoutIMEI',a.id,
         'ACC-'||lpad(a.id::text,6,'0')||' is With Device but has no linked phone IMEI.'
  from public.accessory_assets a
  where a.status='With Device' and coalesce(trim(a.device_imei),'')=''

  union all
  select 'High','MissingLinkedDevice',a.id,
         'ACC-'||lpad(a.id::text,6,'0')||' links to IMEI '||coalesce(a.device_imei,'')||' which is not in Inventory.'
  from public.accessory_assets a
  where a.status='With Device'
    and coalesce(trim(a.device_imei),'')<>''
    and not exists(
      select 1 from public.devices d
      where regexp_replace(coalesce(d.imei1,''),'\D','','g')=regexp_replace(coalesce(a.device_imei,''),'\D','','g')
         or regexp_replace(coalesce(d.imei2,''),'\D','','g')=regexp_replace(coalesce(a.device_imei,''),'\D','','g')
    )

  union all
  select 'High','WrongEmployeeForPhone',a.id,
         'ACC-'||lpad(a.id::text,6,'0')||' is linked to a phone assigned to a different employee.'
  from public.accessory_assets a
  join public.devices d on regexp_replace(coalesce(d.imei1,''),'\D','','g')=regexp_replace(coalesce(a.device_imei,''),'\D','','g')
  where a.status='With Device' and d.status='Assigned'
    and coalesce(trim(a.assigned_employee_id),'')<>''
    and lower(trim(a.assigned_employee_id))<>lower(trim(coalesce(d.assigned_employee_id,'')))

  union all
  select 'High','DuplicateSIMInDeviceInventory',min(a.id),
         'SIM '||sim.sim_no||' is recorded on more than one phone in Device Inventory.'
  from (
    select regexp_replace(s.value,'\D','','g') sim_no,count(distinct d.id) device_count
    from public.devices d
    cross join lateral jsonb_array_elements_text(coalesce(d.sim_numbers,'[]'::jsonb)) s(value)
    where regexp_replace(s.value,'\D','','g') ~ '^\d{10}$'
      and regexp_replace(s.value,'\D','','g')<>'0000000000'
    group by regexp_replace(s.value,'\D','','g')
    having count(distinct d.id)>1
  ) sim
  left join public.accessory_assets a
    on a.asset_type='SIM Card' and regexp_replace(coalesce(a.identifier,''),'\D','','g')=sim.sim_no
  group by sim.sim_no

  union all
  select 'Medium','ExitedEmployeeStillOwnsAsset',a.id,
         'ACC-'||lpad(a.id::text,6,'0')||' is still assigned to exited employee '||coalesce(a.assigned_employee_id,'')||'. Review takeover status.'
  from public.accessory_assets a
  join public.employee_it_status e on lower(trim(e.employee_id))=lower(trim(a.assigned_employee_id))
  where e.status='Exited' and a.status in ('Assigned','With Device');
$$;

grant execute on function public.dncc_assign_accessory(bigint,text,text,text,text,text,text,text) to anon,authenticated;
grant execute on function public.dncc_return_accessory(bigint,text,text,text) to anon,authenticated;
grant execute on function public.dncc_reconcile_accessory_registry() to anon,authenticated;
grant execute on function public.dncc_accessory_health() to anon,authenticated;

-- One-time safe reconciliation. No charger/cable possession is guessed.
select public.dncc_reconcile_accessory_registry();
notify pgrst,'reload schema';
